version: '3'

services:
  reservas-database:
    image: mysql
    container_name: reservas-database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ucr_reservas   
      MYSQL_USER: reservas_user
      MYSQL_PASSWORD: UDCW6fqxXOSs
    ports:
      - 3306:3306
    volumes:
     - reservas_db:/var/lib/mysql
    networks:
     - backendNetwork
     
  reservas-application-backend:
    image: azul/zulu-openjdk:17
    container_name: reservas-application-backend
    ports:
      - 8080:8080
    depends_on:
      - reservas-database
    volumes:
      - ./backend/target/backend-1.0-SNAPSHOT.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - backendNetwork
      - frontendNetwork
      
  reservas-application-frontend:
    image: nginx:alpine
    container_name: reservas-application-frontend
    ports: 
      - 4200:80
    depends_on:
      - reservas-application-backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/:/usr/share/nginx/html
    networks:
      - frontendNetwork

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./backend/spec/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json


volumes:
  reservas_db:
  
networks:
  backendNetwork:
  frontendNetwork: